### ISSUE TITLE
"There is no Wiimote currently attached to the computer" when running a x86 build.

### ISSUE THREAD

**Issue by ghost** [madmaxoft/WiiWhiteboard#1]
Hi ,I am building for x86 systems and it is just not detecting connected wiimotes.It is working flawlessly on x64 though.Any ideas on what one may tweak to make this work?Thanks
Seems that 
`auto ids = mgr.enumWiimotes();`
is returning an empty vector and I don't know why yet.

**Comment by madmaxoft** [comment]
Hi, sorry for the late reply.

I'm afraid I don't have a 32-bit system to test this on. My guess is that either the API there is different, or perhaps the driver reports a different ID so the software doesn't recognize it.

First of all, check if your controller is already paired through Bluetooth. It should appear in "Devices and Printers" (Win7) as "Nintendo RVL_CNT-01".
Then go to the Computer Management (run `compmgmt.msc`), go to the Device manager node in the tree, select menu View -> Devices by connection, then locate the bluetooth adapter and under it, there should be a "Bluetooth HID Device" representing the Wiimote, with a "HID-compliant game controller" node under it. This is your Wiimote:
![wiimote-devmgr](https://cloud.githubusercontent.com/assets/4388386/21046646/ef151580-be05-11e6-80fc-ee1e07b803d1.png)
Open the node's Properties dialog, select the Details tab and choose the "Hardware Ids" property from the drop-down. Verify that there is a `057e` after `VID` and `0306` after `PID`, for both of them:
![wiimote-props](https://cloud.githubusercontent.com/assets/4388386/21046741/6d3a4002-be06-11e6-9687-cfcca13e9c5a.png)
These are exactly the steps that WiiWhiteboard takes to detect devices, so if there is something different on your system, it's the cause of this issue. Let me know if your values are the same or not.

**Comment by madmaxoft** [comment]
Another thing you could try: Install DebugView from SysInternals: https://technet.microsoft.com/en-us/sysinternals/debugview.aspx
Run it, and then run WiiWhiteboard. DebugView will show logging output from WiiWhiteboard, copy and paste it here for analysis.

**Comment by ghost** [comment]
Thanks for the detailed reply,I am using the bluesoleil bluetooth stack for my connections.The device info I have is show below and it doesn't look like yours ( 057e after VID and 0306 after PID).This is strange because if I compile the 64 bit version it runs fine.My guess some used APIs behave differently on 32bit and 64 bit.

![image](https://cloud.githubusercontent.com/assets/3991041/21071119/cbcdbcea-bed1-11e6-9e3f-72e82c310a01.png)

**I'm afraid I don't have a 32-bit system to test this on**
I am not an expert on this ,but I think you can swith the architecture you are compiling for in visual studio and a 32bit program will run on a 64bit system just fine.May be you can give it a try.
I am going to try debugView right now and get back at you.

**Comment by ghost** [comment]
DebugView just gives 
`[\\COMPUTERNAME]
00000002	23.06419563	[6532] Main.cpp(23): WinMain: Detecting Wiimotes...`

The program runs and a dialog with the message is shown.
![image](https://cloud.githubusercontent.com/assets/3991041/21071240/9318cdbe-bed5-11e6-87d8-818fcb466f34.png)

The program exits as long as you click on the OK button.

**Comment by madmaxoft** [comment]
Wait, so are you trying a 32-bit app on a 64-bit OS? Or 32-bit app on a 32-bit OS?

As for the device manager screenshot, it seems like you don't have the Wiimote paired in your system - it should appear as a child node of the bluetooth adapter, there's nothing there in your screenshot. Your VID/PID dialog screenshot has no relevance, as it is for the bluetooth adapter itself, not for the Wiimote.

**Comment by ghost** [comment]
I am running a 32 bit exe on a 64 bit system.

**Comment by madmaxoft** [comment]
Right, there was actually an error, I fixed it in current master, 4927aa70faf10a57fb47569b7d83b22469f8f930.

Please try updating your sources and recompiling.

**Comment by ghost** [comment]
After applying 4927aa7  I can now successfully run the app on 32bit systems.Thanks for the fix.
